# name: Deploy

# on:
#   push:
#     branches: [master]

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v1

#       - name: Install dependencies
#         run: yarn

#       - name: Build
#         run: yarn build

#       - name: Percy Visual Regressions
#         uses: percy/snapshot-action@v0.1.1
#         with:
#           build-directory: "public"
#         env:
#           PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

#       - name: Cypress run
#         uses: cypress-io/github-action@v1
#         with:
#           start: npm run develop
#           wait-on: http://localhost:8000
#           wait-on-timeout: 120

#   build-and-deploy:
#     runs-on: ubuntu-latest
#     needs: test

#     steps:
#       - uses: actions/checkout@v2
#       - uses: fregante/setup-git-token@v1
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#       - uses: actions/setup-node@v1

#       - name: Install dependencies
#         run: yarn

#       - name: Build
#         run: yarn build

#       - name: Deploy
#         run: yarn deploy

#         env:
#           CI: true
