name: Test + Deploy Website

on:
  push:
    branches: [master]
    paths:
      - packages/website/**
      - yarn.lock

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build
          working-directory: packages/website

      - name: Percy Visual Regressions
        uses: percy/snapshot-action@v0.1.1
        with:
          build-directory: "packages/website/public"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v1

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build
          working-directory: packages/website

      - name: Deploy
        run: yarn deploy
          working-directory: packages/website
          
        env:
          CI: true
